{{- $global := .Values.global | default dict }}
{{- $globalValues := dict }}
{{- if $global.registry }}
{{- $globalValues = printf `
global:
  registry: $R
  imageRegistry: $R
  image:
    registry: $R
  hub: $R/istio
grafana-operator:
  image:
    repository: $R/grafana/grafana-operator
external-dns:
  image:
    repository: $R/external-dns/external-dns
jaeger-operator:
  image:
    repository: $R/jaegertracing/jaeger-operator
opencost:
  opencost:
    exporter:
      image:
        registry: $R
    ui:
      image:
        registry: $R
opentelemetry-operator:
  manager:
    image:
      repository: $R/opentelemetry-operator/opentelemetry-operator
    collectorImage:
      repository: $R/otel/opentelemetry-collector-contrib
  kubeRBACProxy:
    image:
      repository: $R/brancz/kube-rbac-proxy
` | replace "$R" $global.registry | fromYaml }}
{{- end -}}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: kof-regional-cluster
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: regional
    matchExpressions:
      - key: "k0rdent.mirantis.com/istio-role"
        operator: DoesNotExist

  serviceSpec:
    services:

      {{- if (index .Values "cert-manager" "enabled") }}
      - name: cert-manager
        namespace: {{ .Release.Namespace }}
        template: {{ index .Values "cert-manager" "template" }}
        values: |
          crds:
            enabled: true
      {{- end }}

      {{- if (index .Values "ingress-nginx" "enabled") }}
      - name: ingress-nginx
        namespace: {{ .Release.Namespace }}
        template: {{ index .Values "ingress-nginx" "template" }}
        values: |
          {{`{{ if eq .InfrastructureProvider.kind "AzureCluster" }}`}}
          # Workaround for https://github.com/k0rdent/kcm/issues/1119#issuecomment-2721512663
          controller:
            service:
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
          {{`{{ end }}`}}
      {{- end }}

      - name: kof-storage
        namespace: {{ .Release.Namespace }}
        template: kof-storage-{{ .Chart.Version | replace "." "-" }}
        values: |
          {{`{{ $storageClass := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-storage-class" | default "" }}`}}
          {{`{{ $regionalDomain := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-regional-domain" }}`}}
          {{`{{ $tracesEnabled := not (index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-write-traces-endpoint") }}`}}
          {{`{{ $tracesHost := $tracesEnabled | ternary (printf "jaeger.%s" $regionalDomain) "" }}`}}
          {{`{{ $metricsEnabled := not (index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-write-metrics-endpoint") }}`}}
          {{`{{ $metricsHost := $metricsEnabled | ternary (printf "vmauth.%s" $regionalDomain) "" }}`}}
          {{`{{ $grafanaHost := printf "grafana.%s" $regionalDomain }}`}}
          {{`{{ $certEmail := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-cert-email" }}`}}
          {{`{{ $storageValuesFromAnnotation := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-storage-values" | default "{}" | fromYaml }}`}}
          {{`{{`}} $storageValuesFromHelm := `{{ .Values.storage | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} $storageValuesHere := printf `
          global:
            storageClass: %q
          victoria-logs-cluster:
            vlstorage:
              persistentVolume:
                storageClassName: %q
          external-dns:
            enabled: true
          jaeger:
            ingress:
              enabled: %t
              host: %q
          victoriametrics:
            vmauth:
              ingress:
                enabled: %t
                host: %q
          grafana:
            ingress:
              host: %q
          cert-manager:
            email: %q
          ` $storageClass $storageClass $tracesEnabled $tracesHost $metricsEnabled $metricsHost $grafanaHost $certEmail | fromYaml {{`}}`}}
          {{`{{`}} $globalValuesFromHelm := `{{ $globalValues | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{ mergeOverwrite (dict) $globalValuesFromHelm $storageValuesHere $storageValuesFromHelm $storageValuesFromAnnotation | toYaml | nindent 4 }}`}}

      - name: kof-operators
        namespace: {{ .Release.Namespace }}
        template: kof-operators-{{ .Chart.Version | replace "." "-" }}
        {{- with $globalValues }}
        values: |
          {{- . | toYaml | nindent 10 }}
        {{- end }}

      - name: kof-collectors
        namespace: {{ .Release.Namespace }}
        template: kof-collectors-{{ .Chart.Version | replace "." "-" }}
        values: |
          {{`{{ $collectorsValuesFromAnnotation := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-collectors-values" | default "{}" | fromYaml }}`}}
          {{`{{`}} $collectorsValuesFromHelm := `{{ .Values.collectors | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} $collectorsValuesHere := printf `
          global:
            clusterName: %q
          opencost:
            opencost:
              exporter:
                defaultClusterId: %q
          ` .Cluster.metadata.name .Cluster.metadata.name | fromYaml {{`}}`}}
          {{`{{`}} $globalValuesFromHelm := `{{ $globalValues | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{ mergeOverwrite (dict) $globalValuesFromHelm $collectorsValuesHere $collectorsValuesFromHelm $collectorsValuesFromAnnotation | toYaml | nindent 4 }}`}}
