apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-storage-secrets: "true"
    k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
    k0rdent.mirantis.com/kof-cluster-role: regional
spec:
  credential: aws-cluster-identity-cred
  template: aws-standalone-cp-0-1-5
  config:
    clusterAnnotations:
      k0rdent.mirantis.com/kof-regional-domain: "aws-ue2.kof.example.com"
      k0rdent.mirantis.com/kof-cert-email: mail@example.com
      # Optional custom endpoints:
      # k0rdent.mirantis.com/kof-logs-endpoint: https://vmauth.aws-ue2.kof.example.com/vls
      # k0rdent.mirantis.com/kof-metrics-endpoint: https://vmauth.aws-ue2.kof.example.com/vm/select/0/prometheus
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: false
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
