apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-eks-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-storage-secrets: "true"
    k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
    k0rdent.mirantis.com/kof-cluster-role: regional
spec:
  template: aws-eks-0-1-2
  credential: aws-cluster-identity-cred
  config:
    clusterAnnotations:
      k0rdent.mirantis.com/kof-regional-domain: aws-eks-ue2.kof.example.com
      k0rdent.mirantis.com/kof-cert-email: mail@example.com
      k0rdent.mirantis.com/kof-storage-class: gp2

      # Default endpoints for `kof-regional-domain: aws-eks-ue2.kof.example.com`:
      # kof-write-metrics-endpoint: https://vmauth.aws-eks-ue2.kof.example.com/vm/insert/0/prometheus/api/v1/write
      # kof-read-metrics-endpoint: https://vmauth.aws-eks-ue2.kof.example.com/vm/select/0/prometheus
      # kof-write-logs-endpoint: https://vmauth.aws-eks-ue2.kof.example.com/vls/insert/opentelemetry/v1/logs
      # kof-read-logs-endpoint: https://vmauth.aws-eks-ue2.kof.example.com/vls
      # kof-write-traces-endpoint: https://jaeger.aws-eks-ue2.kof.example.com/collector
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
