apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-eks-ue2
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/kof-storage-secrets: "true"
    k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
    k0rdent.mirantis.com/kof-cluster-role: regional
spec:
  template: aws-eks-0-1-2
  credential: aws-cluster-identity-cred
  config:
    clusterAnnotations:
      k0rdent.mirantis.com/kof-regional-domain: "aws-eks-ue2.kof.example.com"
      k0rdent.mirantis.com/kof-storage-class: gp2
      k0rdent.mirantis.com/kof-cert-email: mail@example.com
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
