apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-eks-ue2
  namespace: kcm-system
  annotations:
    k0rdent.mirantis.com/kof-cert-email: mail@example.net
spec:
  template: aws-eks-0-1-0
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
    clusterLabels:
      k0rdent.mirantis.com/kof-storage-secrets: "true"
      k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
      k0rdent.mirantis.com/kof-cluster-role: regional
      k0rdent.mirantis.com/kof-regional-domain: aws-eks-ue2.kof.example.com
      k0rdent.mirantis.com/kof-dns-enabled: "true"
      k0rdent.mirantis.com/kof-dns-region: us-east-2
      k0rdent.mirantis.com/kof-storage-class: gp2
---
apiVersion: kof.k0rdent.mirantis.com/v1alpha1
kind: PromxyServerGroup
metadata:
  labels:
    app.kubernetes.io/name: kof-operator
    k0rdent.mirantis.com/promxy-secret-name: kof-mothership-promxy-config
  name: promxyservergroup-sample
  namespace: kof
spec:
  cluster_name: storage0
  targets:
    - "vmauth.storage0.example.net:443"
  path_prefix: "/vm/select/0/prometheus/"
  scheme: https
  http_client:
    dial_timeout: "5s"
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      credentials_secret_name: "storage-vmuser-credentials"
      username_key: "username"
      password_key: "password"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: victoria-logs-storage0
  namespace: kof
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          key: username
          name: storage-vmuser-credentials
    - targetPath: "secureJsonData.basicAuthPassword"
      valueFrom:
        secretKeyRef:
          key: password
          name: storage-vmuser-credentials
  datasource:
    access: proxy
    isDefault: false
    name: storage0-logs
    type: "victoriametrics-logs-datasource"
    url: https://vmauth.storage0.example.net/vls
    basicAuth: true
    basicAuthUser: ${username}
    secureJsonData:
      basicAuthPassword: ${password}
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
