apiVersion: v2
name: kof-operators
description: KOF Helm chart that deploys operators and CRDs required by other KOF charts
version: "1.4.0"
appVersion: "1.4.0"
dependencies:
  - name: grafana-operator
    version: "v5.18.0"
    repository: "oci://ghcr.io/grafana/helm-charts"
    condition: grafana-operator.enabled
  - name: opentelemetry-operator
    version: "0.93.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled
  - name: prometheus-operator-crds
    version: "15.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-operator-crds.enabled
