kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta4
    kind: JoinConfiguration
    nodeRegistration:
      criSocket: unix:///run/containerd/containerd.sock
nodes:
  - role: control-plane
    extraMounts: &extraMounts
      - containerPath: /var/lib/kubelet/config.json
        hostPath: /home/runner/.docker/config.json
  - role: worker
    extraMounts: *extraMounts
