apiVersion: v2
name: kof-storage
description: KOF Helm chart with Jaeger and VictoriaMetrics storage
version: "1.4.0"
appVersion: "1.4.0"
dependencies:
  - name: victoria-metrics-operator
    version: "0.43.1"
    repository: "https://victoriametrics.github.io/helm-charts/"
    condition: victoria-metrics-operator.enabled
  - name: victoria-logs-cluster
    version: "0.0.2"
    repository: https://victoriametrics.github.io/helm-charts/
    condition: victoria-logs-cluster.enabled
  - name: external-dns
    version: "1.15.2"
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    condition: external-dns.enabled
  - name: jaeger-operator
    version: "2.50.1"
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger-operator.enabled
  - name: dex
    version: "0.23.0"
    repository: https://charts.dexidp.io
    condition: dex.enabled
  - name: kof-dashboards
    condition: grafana.enabled
    version: "1.4.0"
    repository: file://../kof-dashboards/
