name: Shared setup
description: |
  Setup required for all workflows.
  Some steps may be moved into GitHub runner image eventually.
runs:
  using: composite
  steps:
    - name: Copy docker creds
        # without direct mount from secret
        # to keep `~/.docker` dir writable for `runner` user
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        SECRET=/run/secrets/docker/config.json
        TARGET=/home/runner/.docker
        ls -la "$SECRET"
        mkdir -p "$TARGET"
        cp "$SECRET" "$TARGET"
        echo "ls -la $TARGET"
        ls -la "$TARGET"
        echo "DOCKER_CONFIG=$TARGET" >> "$GITHUB_ENV"

        echo "::group::debug"
        #echo "DOCKER_CONFIG=${DOCKER_CONFIG:-}"
        #echo "docker info --format '{{.RegistryConfig.IndexConfigs}}'"
        #docker info --format '{{.RegistryConfig.IndexConfigs}}'
        #echo "docker --debug --log-level debug pull hello-world:latest"
        #docker --debug --log-level debug pull hello-world:latest
        #echo "ps aux | grep docker"
        #ps aux | grep docker
        #echo "cat $TARGET/config.json"
        #cat "$TARGET/config.json"
        #echo 'Click "Delete all logs" in 3 dots near "Re-run jobs"'
        echo "::endgroup::"

    - name: Install required packages
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        echo "::group::apt"
        sudo apt update -qq
        sudo apt install -qqy build-essential wget
        echo "::endgroup::"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "18.18.2"
