name: Shared setup
description: |
  Setup required for all workflows.
  Some steps may be moved into GitHub runner image eventually.
runs:
  using: composite
  steps:
    - name: Install required packages
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        echo "::group::debug"
        echo "USER=$USER"
        echo "HOME=$HOME"
        ls -la ~/.docker || true
        grep auths ~/.docker/config.json || true
        echo "::endgroup::"

        echo "::group::apt"
        sudo apt update -qq
        sudo apt install -qqy build-essential wget
        echo "::endgroup::"
