name: Shared setup
description: |
  Setup required for all workflows.
  Some steps may be moved into GitHub runner image eventually.
runs:
  using: composite
  steps:
    - name: Configure Docker
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        echo "::group::docker"
        # Option 1.
        # Docker auth could avoid "429 Too Many Requests toomanyrequests:
        #   You have reached your unauthenticated pull rate limit."
        # but mount to `/var/lib/kubelet/config.json` in kind did not help,
        # and even with auth it gives 200 pulls per 6 hours = 33 pulls per hour:
        # not enough with multiple CI jobs in each PR and with other k0rdent repos.
        #
        # MOUNTED_FILE=/run/secrets/docker/config.json
        #   # No direct mount to keep `~/.docker` dir writable for `docker build`.
        # TARGET_DIR=~/.docker
        # ls -la "$MOUNTED_FILE"
        # mkdir -p "$TARGET_DIR"
        # cp "$MOUNTED_FILE" "$TARGET_DIR"
        # echo "ls -la $TARGET_DIR"
        # ls -la "$TARGET_DIR"
        # echo "DOCKER_CONFIG=$TARGET_DIR" >> "$GITHUB_ENV"

        # Option 2.
        # The pull through cache is a more reliable solution.
        # It is configured in `config/kind.yaml` missing in older releases:
        cp config/kind.yaml /tmp/kind.yaml

        # https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
        sudo sysctl fs.inotify.max_user_watches=524288
        sudo sysctl fs.inotify.max_user_instances=512

        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
        chmod +x kind
        kind create cluster -n kcm-dev --config config/kind.yaml
        echo "DEBUG: docker exec kcm-dev-control-plane ulimit -n"
        docker exec kcm-dev-control-plane ulimit -n
        exit 1
        echo "::endgroup::"

    - name: Install required packages
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        echo "::group::apt"
        sudo apt update -qq
        sudo apt install -qqy build-essential wget
        echo "::endgroup::"

    - uses: azure/setup-kubectl@v4

    - uses: actions/setup-node@v6
      with:
        node-version: "18.18.2"
