name: Shared setup
description: |
  Setup required for all workflows.
  Some steps may be moved into the runner image eventually.
runs:
  using: composite
  steps:
    # - name: Install required packages
    #   shell: bash --noprofile --norc -euo pipefail {0}
    #   run: |
    #     echo "::group::apt"
    #     sudo apt update -qq
    #     sudo apt install -qqy build-essential wget
    #     echo "::endgroup::"

    - name: Set shared env vars
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        KCM_NEXT_RELEASE=v1.5.0-release
          # TODO: Set it to `main` after `v1.5.0-release` is merged.
        echo "KCM_NEXT_RELEASE=$KCM_NEXT_RELEASE" >> "$GITHUB_ENV"
        echo "BASE_COMMIT=origin/$KCM_NEXT_RELEASE" >> "$GITHUB_ENV"
        echo "HEAD_COMMIT=origin/$KCM_NEXT_RELEASE" >> "$GITHUB_ENV"

    - name: Copy config missing in older releases
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        # TODO: Delete this step after the latest release includes `config/kind.yaml` file.
        cp config/kind.yaml /tmp/kind.yaml

    - uses: azure/setup-kubectl@v4

    - uses: actions/setup-node@v6
      with:
        node-version: "18.18.2"
