name: Shared setup
description: |
  Setup required for all workflows.
  Some steps may be moved into GitHub runner image eventually.
runs:
  using: composite
  steps:
    - name: Install required packages
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        echo "::group::debug"
        echo "USER=${USER:-}"
        echo "whoami=$(whoami)"
        echo "HOME=${HOME:-}"
        echo "ls -la ~/.docker" && ls -la ~/.docker || true
        echo "ls -la ~/.dockercfg" && ls -la ~/.dockercfg || true
        echo "::endgroup::"

        echo "::group::apt"
        sudo apt update -qq
        sudo apt install -qqy build-essential wget
        echo "::endgroup::"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "18.18.2"
