name: Shared setup
description: |
  Setup required for all workflows.
  Some steps may be moved into GitHub runner image eventually.
runs:
  using: composite
  steps:
    - name: Apply docker config
        # * With auth to avoid "429 Too Many Requests toomanyrequests:
        #   You have reached your unauthenticated pull rate limit."
        # * Without direct mount from secret read-only filesystem
        #   to keep `~/.docker` dir writable for `docker build`.
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        echo "::group::docker"
        MOUNTED_FILE=/run/secrets/docker/config.json
        TARGET_DIR=~/.docker
        ls -la "$MOUNTED_FILE"
        mkdir -p "$TARGET_DIR"
        cp "$MOUNTED_FILE" "$TARGET_DIR"
        echo "ls -la $TARGET_DIR"
        ls -la "$TARGET_DIR"
        echo "DOCKER_CONFIG=$TARGET_DIR" >> "$GITHUB_ENV"
        echo "::endgroup::"

    - name: Install required packages
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        echo "::group::apt"
        sudo apt update -qq
        sudo apt install -qqy build-essential wget
        echo "::endgroup::"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "18.18.2"
