apiVersion: v2
name: kof-collectors
description: KOF Helm chart with OpenTelemetryCollectors and OpenCost
version: "1.5.0-rc2"
appVersion: "1.5.0-rc2"
dependencies:
  - name: opencost
    version: "1.42.3"
    repository: https://opencost.github.io/opencost-helm-chart
    condition: opencost.enabled
  - name: opentelemetry-kube-stack
    version: "0.5.*"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: collectors.enabled
