{{- $global := .Values.global | default dict }}
{{- $globalValues := dict }}
{{- if $global.registry }}
{{- $globalValues = printf `
global:
  registry: $R
  imageRegistry: $R
  image:
    registry: $R
  hub: $R/istio
grafana-operator:
  image:
    repository: $R/grafana/grafana-operator
external-dns:
  image:
    repository: $R/external-dns/external-dns
jaeger-operator:
  image:
    repository: $R/jaegertracing/jaeger-operator
opencost:
  opencost:
    exporter:
      image:
        registry: $R
        tag: "1.113.0@sha256:ee2486ae56b321bb6dde1ccbcc7786577313b5c679f47501696e2b0e87463b7b"
    ui:
      image:
        registry: $R
        tag: "1.113.0@sha256:d57af3bd85b73e726a53b8e5063e0fab19cdaecda34da717ff24ef91a63260a7"
opentelemetry-operator:
  manager:
    image:
      repository: $R/opentelemetry-operator/opentelemetry-operator
    collectorImage:
      repository: $R/otel/opentelemetry-collector-contrib
  kubeRBACProxy:
    image:
      repository: $R/brancz/kube-rbac-proxy
` | replace "$R" $global.registry | fromYaml }}
{{- end -}}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: kof-child-cluster
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
    matchExpressions:
      - key: "k0rdent.mirantis.com/istio-role"
        operator: DoesNotExist

  serviceSpec:
    templateResourceRefs:
      - identifier: ChildConfig
        resource:
          apiVersion: v1
          kind: ConfigMap
          name: kof-cluster-config-{{`{{ .Cluster.metadata.name }}`}}
          namespace: {{ .Values.kcm.namespace }}

    services:

      {{- if (index .Values "cert-manager" "enabled") }}
      - name: cert-manager
        namespace: {{ .Release.Namespace }}
        template: cert-manager-1-16-4
        values: |
          crds:
            enabled: true
      {{- end }}

      - name: kof-operators
        namespace: {{ .Release.Namespace }}
        template: kof-operators-{{ .Chart.Version | replace "." "-" }}
        {{- with $globalValues }}
        values: |
          {{- . | toYaml | nindent 10 }}
        {{- end }}

      - name: kof-collectors
        namespace: {{ .Release.Namespace }}
        template: kof-collectors-{{ .Chart.Version | replace "." "-" }}
        values: |
          {{`{{ $childClusterName := .Cluster.metadata.name }}`}}
          {{`{{ $writeMetricsEndpoint := getField "ChildConfig" "data.write_metrics_endpoint" }}`}}
          {{`{{ $readMetricsEndpoint := getField "ChildConfig" "data.read_metrics_endpoint" }}`}}
          {{`{{ $logsEndpoint := getField "ChildConfig" "data.write_logs_endpoint" }}`}}
          {{`{{ $tracesEndpoint := getField "ChildConfig" "data.write_traces_endpoint" }}`}}
          {{`{{ $collectorsValuesFromAnnotation := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-collectors-values" | default "{}" | fromYaml }}`}}
          {{`{{`}} $collectorsValuesFromHelm := `{{ .Values.collectors | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} $collectorsValuesHere := printf `
          global:
            clusterName: %q
          kof:
            metrics:
              endpoint: %q
            logs:
              endpoint: %q
            traces:
              endpoint: %q
          opencost:
            opencost:
              prometheus:
                external:
                  url: %q
              exporter:
                defaultClusterId: %q
          ` $childClusterName $writeMetricsEndpoint $logsEndpoint $tracesEndpoint $readMetricsEndpoint $childClusterName | fromYaml {{`}}`}}
          {{`{{`}} $globalValuesFromHelm := `{{ $globalValues | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{ mergeOverwrite (dict) $globalValuesFromHelm $collectorsValuesHere $collectorsValuesFromHelm $collectorsValuesFromAnnotation | toYaml | nindent 4 }}`}}
