{{- range $name, $value := .Values.kcm.kof.clusterProfiles }}
{{- /* Distributing secrets to clusters automatically*/}}
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: {{ $name }}
spec:
  clusterSelector:
    matchLabels: {{ $value.matchLabels | toYaml | nindent 6 }}
  templateResourceRefs:
    {{- range $value.secrets }}
    - identifier: secret-{{ . }}
      resource:
        apiVersion: v1
        kind: Secret
        name: {{ . }}
        namespace: {{ $.Release.Namespace }}
    {{- end }}
  policyRefs:
    {{- range $value.secrets }}
    - kind: ConfigMap
      deploymentType: Local
      {{/* `Local` is the management cluster with multiple tenants/namespaces, */}}
      {{/* each having `ClusterDeployments` with related `GrafanaDatasources`, */}}
      {{/* that require the secret to be in the same cluster namespace. */}}
      name: cluster-namespace-secret-template-{{ . }}
      namespace: {{ $.Release.Namespace }}
    - kind: ConfigMap
      deploymentType: Remote
      {{/* `Remote` is a regional/child cluster with release namespace only. */}}
      name: release-namespace-secret-template-{{ . }}
      namespace: {{ $.Release.Namespace }}
    {{- end }}
{{- range $value.secrets }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-namespace-secret-template-{{ . }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  secret.yaml: |
    {{`{{`}} setField "secret-{{ . }}" "metadata.namespace" $.Cluster.metadata.namespace {{`}}`}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-namespace-secret-template-{{ . }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    projectsveltos.io/template: "true"
data:
  secret.yaml: |
    {{`{{`}} setField "secret-{{ . }}" "metadata.namespace" "{{ $.Release.Namespace }}" {{`}}`}}
{{- end }}
{{- end }}
