{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmalert.enabled }}
{{- $global := .Values.global | default dict }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  configMaps: []
  datasource:
    url: http://{{ .Release.Name }}-promxy.{{ .Release.Namespace }}.svc:8082
  evaluationInterval: 15s
  externalLabels: {}
  extraArgs:
    http.pathPrefix: /
    remoteWrite.disablePathAppend: "true"
  image:
    {{- if $global.registry }}
    repository: {{ $global.registry }}/victoriametrics/vmalert
    {{- end }}
    tag: v1.105.0
  configReloaderImageTag: {{ with $global.registry }}{{ . }}/{{ end }}jimmidyson/configmap-reload:v0.3.0
  license: {}
  notifiers:
    - url: http://vmalertmanager-cluster.{{ .Release.Namespace }}.svc:9093
  port: "8080"
  remoteRead:
    url: {{ .Values.victoriametrics.vmalert.remoteRead | default (printf "http://vmselect-cluster.%s.svc:8481/select/0/prometheus" .Release.Namespace) }}
  remoteWrite:
    url: http://vminsert-cluster.{{ .Release.Namespace }}:8480/insert/0/prometheus/api/v1/write
  selectAllByDefault: true
{{- end }}
{{- end }}
