{{- $global := .Values.global | default dict }}
{{- if .Values.victoriametrics.enabled }}
{{- if .Values.victoriametrics.vmalert.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  configRawYaml: |-
{{ .Values.victoriametrics.vmalert.vmalertmanager.config | nindent 4 }}
  image:
    repository: {{ with $global.registry }}{{ . }}/{{ end }}prom/alertmanager
    tag: v0.27.0
  configReloaderImageTag: {{ with $global.registry }}{{ . }}/{{ end }}jimmidyson/configmap-reload:v0.3.0
  port: "9093"
{{- end }}
{{- end }}
